server:
    port: 8080

spring:
    application:
        name: S-W-R-Social-Network-API
    datasource:
        initialization-mode: always
    jpa:
        show-sql: false
        open-in-view: true
    profiles:
        active: test #dev or test
    hibernate:
        ddl-auto: none #change to validate when dev ou prod profile as active or change to none when test profile is active
        use-new-id-generator-mappings: false
    flyway:
        enabled: false #change to false when test profile as active or change to true when dev profile is active
        baseline-on-migrate: false
        locations: classpath:/db/migration

    cache:
        type: redis

    redis:
        host: localhost
        port: 6379

renegade:
    value: 3
