server:
    port: 8080

spring:
    application:
        name: S-W-R-Social-Network-API
    datasource:
        initialization-mode: always
    jpa:
        show-sql: false
        open-in-view: true
        hibernate:
            ddl-auto: validate
            use-new-id-generator-mappings: false
    profiles:
        active: dev
    flyway:
        enabled: true
        baseline-on-migrate: false
        locations: classpath:/db/migration

renegade:
    value: 3
